//! Code generation from Bedrock protocol schemas.
//!
//! Reads a parsed `Schema` and generates Rust source code for enums, types,
//! packets, and the packet factory. Designed to be used from `build.rs`.

mod gen;
pub mod naming;
pub mod type_mapping;

use bedrock_protocol_schema::Schema;
use std::io::{self, Write};
use std::path::Path;

/// Error type for code generation.
#[derive(Debug)]
pub enum GenError {
    Io(io::Error),
    Schema(String),
}

impl From<io::Error> for GenError {
    fn from(e: io::Error) -> Self {
        GenError::Io(e)
    }
}

impl std::fmt::Display for GenError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            GenError::Io(e) => write!(f, "IO error: {}", e),
            GenError::Schema(s) => write!(f, "Schema error: {}", s),
        }
    }
}

impl std::error::Error for GenError {}

/// Generate all Rust source files from the schema and write them to `output_dir`.
pub fn generate_all(schema: &Schema, output_dir: &Path) -> Result<(), GenError> {
    // Generate enums (optional, use --features generated-enums)
    {
        let code = gen::enums::generate(&schema.enums);
        let mut file = create_file(output_dir, "enums.rs")?;
        file.write_all(code.as_bytes())?;
    }

    // Generate types (optional, use --features generated-types)
    {
        let code = gen::types::generate(&schema.types, schema);
        let mut file = create_file(output_dir, "types.rs")?;
        file.write_all(code.as_bytes())?;
    }

    // Generate packets (core — always generated when feature enabled)
    {
        let code = gen::packets::generate(schema);
        let mut file = create_file(output_dir, "packets.rs")?;
        file.write_all(code.as_bytes())?;
    }

    // Generate factory
    {
        let code = gen::factory::generate_with_ids(schema);
        let mut file = create_file(output_dir, "factory.rs")?;
        file.write_all(code.as_bytes())?;
    }

    // Generate type stubs (for types referenced by packets but not defined elsewhere)
    {
        let code = gen::stubs::generate_stubs(schema);
        let mut file = create_file(output_dir, "stubs.rs")?;
        file.write_all(code.as_bytes())?;
    }

    // Generate MinecraftPacketIds from packet definitions
    {
        let code = gen::packet_ids::generate(schema);
        let mut file = create_file(output_dir, "packet_ids.rs")?;
        file.write_all(code.as_bytes())?;
    }

    // Generate main module
    {
        let code = String::from(
            "// This file is @generated by bedrock-codegen. Do not edit.\n\n\
             #[path = \"enums.rs\"]     pub mod gen_enums;\n\
             #[path = \"types.rs\"]     pub mod gen_types;\n\
             #[path = \"stubs.rs\"]     pub mod gen_stubs;\n\
             #[path = \"packet_ids.rs\"] pub mod gen_packet_ids;\n\
             #[path = \"packets.rs\"]   pub mod gen_packets;\n\
             #[path = \"factory.rs\"]   pub mod gen_factory;\n",
        );
        let mut file = create_file(output_dir, "generated.rs")?;
        file.write_all(code.as_bytes())?;
    }

    Ok(())
}

/// Generate only enums source to a writer (for testing/embedding).
pub fn generate_enums_to<W: Write>(schema: &Schema, writer: &mut W) -> io::Result<()> {
    let code = gen::enums::generate(&schema.enums);
    writer.write_all(code.as_bytes())
}

/// Generate only types source to a writer.
pub fn generate_types_to<W: Write>(schema: &Schema, writer: &mut W) -> io::Result<()> {
    let code = gen::types::generate(&schema.types, schema);
    writer.write_all(code.as_bytes())
}

/// Generate only packets source to a writer.
pub fn generate_packets_to<W: Write>(schema: &Schema, writer: &mut W) -> io::Result<()> {
    let code = gen::packets::generate(schema);
    writer.write_all(code.as_bytes())
}

/// Generate only factory source to a writer.
pub fn generate_factory_to<W: Write>(schema: &Schema, writer: &mut W) -> io::Result<()> {
    let code = gen::factory::generate(schema);
    writer.write_all(code.as_bytes())
}

fn create_file(dir: &Path, name: &str) -> io::Result<std::fs::File> {
    std::fs::create_dir_all(dir)?;
    std::fs::File::create(dir.join(name))
}

#[cfg(test)]
mod e2e_tests {
    use super::*;

    #[test]
    fn test_generate_all_from_protocol_docs() {
        let manifest_dir = Path::new(env!("CARGO_MANIFEST_DIR"));
        let docs_path = manifest_dir
            .parent()
            .and_then(|p| p.parent())
            .map(|p| p.join("docs").join("protocol-docs"))
            .expect("Cannot resolve protocol-docs path");

        let schema = Schema::load_all(&docs_path).expect("Failed to load schema");

        let tmp = std::env::temp_dir().join("bedrock-codegen-e2e");
        let _ = std::fs::remove_dir_all(&tmp);

        generate_all(&schema, &tmp).expect("generate_all failed");

        // Verify all files exist and have content
        for name in &["generated.rs", "enums.rs", "types.rs", "packets.rs", "factory.rs"] {
            let path = tmp.join(name);
            assert!(path.exists(), "Missing: {}", name);
            let content = std::fs::read_to_string(&path).unwrap();
            assert!(!content.is_empty(), "Empty file: {}", name);
            let lines = content.lines().count();
            eprintln!("{}: {} lines", name, lines);
        }

        eprintln!("Packets: {}, Enums: {}, Types: {}",
            schema.packet_count(), schema.enum_count(), schema.type_count());

        let _ = std::fs::remove_dir_all(&tmp)
            .map_err(|e| eprintln!("Warning: cleanup failed: {}", e));
    }
}
