//! Pre-generated Bedrock protocol version data.
//!
//! This crate contains embedded JSON blobs for one or more protocol versions.
//! Each blob is a serialized `EmbeddedVersion` generated by the `generate-data` binary.
//! The data is committed to git and compiled into the binary via `include_str!()`.
//!
//! # Usage
//!
//! ```rust
//! use bedrock_protocol_data::registry;
//!
//! let reg = registry();
//! let schema = reg.get(975).unwrap();
//! let latest = reg.latest();
//! ```
//!
//! # Adding a new version
//!
//! ```bash
//! # From workspace root:
//! cargo run -p bedrock-protocol-data -- generate-data \
//!   --docs ./docs/protocol-docs \
//!   --output ./crates/bedrock-protocol-data/data/v1001.json
//! ```
//!
//! Then commit the generated file and update `src/lib.rs` to include it.

use bedrock_protocol_schema::registry::ProtocolRegistry;

/// Build a registry containing all embedded protocol versions.
///
/// Each version's data file is stored in `data/v{N}.json` and compiled in
/// via `include_str!()` — zero runtime filesystem access.
pub fn registry() -> ProtocolRegistry {
    // ── All available protocol versions (ordered ascending) ──────────
    let blobs: &[&str] = &[
        include_str!("../data/v897.json"),   // r21_u13  (1.21.130.28)
        include_str!("../data/v924.json"),   // r26_u0   (1.26.0.29)
        include_str!("../data/v944.json"),   // r26_u1   (1.26.10.27)
        include_str!("../data/v975.json"),   // r26_u2   (1.26.20.28) ← current
        include_str!("../data/v1001.json"),  // r26_u3   (1.26.30.30)
    ];
    // ──────────────────────────────────────────────────────────────────

    ProtocolRegistry::from_embedded(blobs)
        .expect("Failed to build protocol registry from embedded data")
}
